openapi: "3.0.2"
info:
  title: MCP Mappings API
  description: API to get/set MCP mappings for Minecraft
  version: 1.0.0
servers:
  - url: https://mcp.thiakil.com/api
    description: Placeholder
paths:
  /versions:
    get:
      summary: Returns a list of Minecraft versions supported.
      operationId: get-versions
      x-irc-equiv: versions
      tags:
        - Versions
      responses:
        200:
         description: Successful response
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/VersionList'
  /{version}/classes:
    get:
      summary: Get a list of classes
      operationId: get-classes
      tags:
        - Classes
      parameters:
        - $ref: '#/components/parameters/mcversion'
      responses:
        200:
          description: A list of class names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              example:
                - "net/minecraft/util/text/TextFormatting"
                - "net/minecraft/crash/CrashReport"
                - "net/minecraft/crash/CrashReportCategory"
                - "net/minecraft/crash/CrashReportCategory$Entry"

  /{version}/classes/{classname}:
    get:
      summary: Get class info
      operationId: get-class
      x-irc-equiv: gc
      tags:
        - Classes
      parameters:
        - $ref: '#/components/parameters/mcversion'
        - name: classname
          in: path
          description: The classname to retrieve. Can be fully qualified (dot separated) or without package.
          schema:
            type: string
          required: true
      responses:
        200:
          description: Class information
          content:
            application/json:
              schema:
                type: object
                properties:
                  obfName:
                    type: string
                    description: Obfuscated Mojang name
                    required: true
                  srgName:
                    type: string
                    description: SRG name
                    required: true
                  interfaces:
                    description: Interfaces implemented directly
                    type: array
                    items:
                      type: string
                  extendedBy:
                    description: Classes that extend this class
                    type: array
                    items:
                      type: string
        404:
          description: Class name not found

  /{version}/fields:
    get:
      summary: Get list of fields
      tags: - Fields
      operationId: get-fields
      parameters:
        - $ref: '#/components/parameters/mcversion'
      responses:
        200:
          description: Field list
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                description: Array of srg names

  /{version}/fields/{fieldname}:
    parameters:
      - $ref: '#/components/parameters/mcversion'
      - name: fieldname
        in: path
        description: The field SRG name to retrieve
        schema:
          type: string
        required: true
    get:
      summary: Get field info
      operationId: get-field
      x-irc-equiv: gf
      tags:
        - Fields
      responses:
        200:
          description: Field information
          content:
            application/json:
              schema:
                type: object
                properties:
                  obfName:
                    type: string
                    description: Obfuscated Mojang name
                    required: true
                  srgName:
                    type: string
                    description: SRG name
                    required: true
                  mappedName:
                    type: string
                    description: The MCP name, if assigned
                  comment:
                    type: string
                    description: The MCP field comment, if assigned
        404:
          description: Field name not found
    post:
      summary: Set field info
      operationId: set-field
      x-irc-equiv: sf
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mcpName:
                  type: string
                  description: New MCP name to set, ignored if same as existing name
                comment:
                  type: string
                  description: Field comment to set
      responses:
        204:
          description: Operation was successful
        403:
          description: Operation failed due to permission error - e.g. MCP name already set but request body contains new name & user is not authorised to do so
        404:
          description: Field name not found


components:
  parameters:
    mcversion:
      name: version
      in: path
      schema:
        type: string
      required: true
  schemas:
    VersionList:
      description: A list of minecraft versions
      type: array
      items:
        $ref: '#/components/schemas/Version'
      example:
        - slug: "1.12.2"
          major: 1
          minor: 12
          patch: 2
        - slug: "1.13"
          major: 1
          minor: 12
    Version:
      type: object
      description: A Semantic Version-like version
      properties:
        slug:
          type: string
          description: The URL Path Parameter for this version & string representation.
        major:
          type: integer
          description: Major version number. The first dot separated number.
        minor:
          type: integer
          description: Minor version number. The second dot separated number.
        patch:
          type: integer
          description: Patch version number. The third dot separated number.
      required:
        - slug
        - major
        - minor
      example:
        slug: "1.12.2"
        major: 1
        minor: 12
        patch: 2